### ISSUE TITLE
Implement FreeList allocator for objects

### ISSUE THREAD

**Issue by c71n93** [Tea-club/ChaiVM#109]
Implement FreeList allocator. It will be necessary to implement Mark-Sweep GC.

**Comment by olisvalue** [comment]
░░░░░░░░░░▀▀▀██████▄▄▄░░░░░░░░░░
░░░░░░░░░░░░░░░░░▀▀▀████▄░░░░░░░
░░░░░░░░░░▄███████▀░░░▀███▄░░░░░
░░░░░░░░▄███████▀░░░░░░░▀███▄░░░
░░░░░░▄████████░░░░░░░░░░░███▄░░
░░░░░██████████▄░░░░░░░░░░░███▌░
░░░░░▀█████▀░▀███▄░░░░░░░░░▐███░
░░░░░░░▀█▀░░░░░▀███▄░░░░░░░▐███░
░░░░░░░░░░░░░░░░░▀███▄░░░░░███▌░
░░░░▄██▄░░░░░░░░░░░▀███▄░░▐███░░
░░▄██████▄░░░░░░░░░░░▀███▄███░░░
░█████▀▀████▄▄░░░░░░░░▄█████░░░░
░████▀░░░▀▀█████▄▄▄▄█████████▄░░
░░▀▀░░░░░░░░░▀▀██████▀▀░░░▀▀██░░
