### ISSUE TITLE
Init repo

### ISSUE THREAD

**Issue by levBagryansky** [Tea-club/ChaiVM#2]
We need to build project sceleton firstly

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#4](https://github.com/Tea-club/ChaiVM/issues/4) is still not solved.

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#6](https://github.com/Tea-club/ChaiVM/issues/6) is still not solved; solved: [#4](https://github.com/Tea-club/ChaiVM/issues/4).

**Comment by 0pdd** [comment]
@levBagryansky all 2 puzzles are solved here: [#4](https://github.com/Tea-club/ChaiVM/issues/4), [#6](https://github.com/Tea-club/ChaiVM/issues/6).
