### ISSUE TITLE
Add memory checking

### ISSUE THREAD

**Issue by levBagryansky** [Tea-club/ChaiVM#37]

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#39](https://github.com/Tea-club/ChaiVM/issues/39) is still not solved.

**Comment by 0pdd** [comment]
@levBagryansky 2 puzzles [#45](https://github.com/Tea-club/ChaiVM/issues/45), [#46](https://github.com/Tea-club/ChaiVM/issues/46) are still not solved; solved: [#39](https://github.com/Tea-club/ChaiVM/issues/39).
