### ISSUE TITLE
Implement Frontend  for bytecode (assembler)

### ISSUE THREAD

**Issue by c71n93** [Tea-club/ChaiVM#41]

**Comment by 0pdd** [comment]
@c71n93 6 puzzles [#70](https://github.com/Tea-club/ChaiVM/issues/70), [#71](https://github.com/Tea-club/ChaiVM/issues/71), [#72](https://github.com/Tea-club/ChaiVM/issues/72), [#73](https://github.com/Tea-club/ChaiVM/issues/73), [#74](https://github.com/Tea-club/ChaiVM/issues/74), [#75](https://github.com/Tea-club/ChaiVM/issues/75) are still not solved.

**Comment by 0pdd** [comment]
@c71n93 4 puzzles [#70](https://github.com/Tea-club/ChaiVM/issues/70), [#71](https://github.com/Tea-club/ChaiVM/issues/71), [#74](https://github.com/Tea-club/ChaiVM/issues/74), [#75](https://github.com/Tea-club/ChaiVM/issues/75) are still not solved; solved: [#72](https://github.com/Tea-club/ChaiVM/issues/72), [#73](https://github.com/Tea-club/ChaiVM/issues/73).

**Comment by 0pdd** [comment]
@c71n93 3 puzzles [#70](https://github.com/Tea-club/ChaiVM/issues/70), [#74](https://github.com/Tea-club/ChaiVM/issues/74), [#75](https://github.com/Tea-club/ChaiVM/issues/75) are still not solved; solved: [#71](https://github.com/Tea-club/ChaiVM/issues/71), [#72](https://github.com/Tea-club/ChaiVM/issues/72), [#73](https://github.com/Tea-club/ChaiVM/issues/73).
