### ISSUE TITLE
Add condition instructions

### ISSUE THREAD

**Issue by levBagryansky** [Tea-club/ChaiVM#42]
We should add condition instructions to our ISA

**Comment by levBagryansky** [comment]
@c71n93 
I think the following instructions are necessary here.
| byte 0 | byte 1| byte 2| byte 3 | Description |
|:------------:|:-----:|:--------------------|:-----------------|:-----------------|
| if_icmpeq | r1 | branch1 | branch 2 | (long operation) if acc == r1 then branch1, otherwise branch2 | 
| if_icmpne | r1 | branch1 | branch 2 | (long operation) if acc != r1 then branch1, otherwise branch2 | 
| if_icmpgt | r1 | branch1 | branch 2 |  (long operation) if acc > r1 then branch1, otherwise branch2 |
| if_icmpge | r1 | branch1 | branch 2 |  (long operation) if acc >= r1 then branch1, otherwise branch2 |
| if_icmplt | r1 | branch1 | branch 2 |  (long operation) if acc < r1 then branch1, otherwise branch2 |
| if_icmple | r1 | branch1 | branch 2 |  (long operation) if acc <= r1 then branch1, otherwise branch2 |
| if_acmpeq | r1 | branch1 | branch 2 |  (object ref. operation) if acc == r1 then branch1, otherwise branch2 |
| if_acmpne | r1 | branch1 | branch 2 |  (object ref. operation) if acc == r1 then branch1, otherwise branch2 |
| dcmpg | r1 | | | compare floats acc with r1. Acc became 1 if greater than r1, 0 if equal, otherwise -1 |
| dcmpl | r1 | | | compare floats acc with r1. Acc became 1 if less than r1, 0 if equal, otherwise -1 |
We can later add other operations including operations with immidiate.

**Comment by c71n93** [comment]
@levBagryansky LGTM

**Comment by 0pdd** [comment]
@levBagryansky 3 puzzles [#52](https://github.com/Tea-club/ChaiVM/issues/52), [#53](https://github.com/Tea-club/ChaiVM/issues/53), [#54](https://github.com/Tea-club/ChaiVM/issues/54) are still not solved.

**Comment by 0pdd** [comment]
@levBagryansky 4 puzzles [#52](https://github.com/Tea-club/ChaiVM/issues/52), [#53](https://github.com/Tea-club/ChaiVM/issues/53), [#82](https://github.com/Tea-club/ChaiVM/issues/82), [#83](https://github.com/Tea-club/ChaiVM/issues/83) are still not solved; solved: [#54](https://github.com/Tea-club/ChaiVM/issues/54).

**Comment by 0pdd** [comment]
@levBagryansky 5 puzzles [#115](https://github.com/Tea-club/ChaiVM/issues/115), [#52](https://github.com/Tea-club/ChaiVM/issues/52), [#53](https://github.com/Tea-club/ChaiVM/issues/53), [#82](https://github.com/Tea-club/ChaiVM/issues/82), [#83](https://github.com/Tea-club/ChaiVM/issues/83) are still not solved; solved: [#54](https://github.com/Tea-club/ChaiVM/issues/54).
