### ISSUE TITLE
assembler.hpp:43-44: Refactor this function. Or maybe it...

### ISSUE THREAD

**Issue by 0pdd** [Tea-club/ChaiVM#71]
The puzzle `41-4dc1c56c` from #41 has to be resolved: 

https://github.com/Tea-club/ChaiVM/blob/ee0e232267a266d4ca6d5ab0ac9d3d22ee3c0b26/include/frontend/assembler/assembler.hpp#L43-L44

The puzzle was created by Roman Korostinskiy on 19-Dec-23. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@levbagryansky @c71n93 please pay attention to this new issue.

**Comment by levBagryansky** [comment]
@c71n93 What's up with this issue
