### ISSUE TITLE
Implement Executor

### ISSUE THREAD

**Issue by c71n93** [Tea-club/ChaiVM#8]
Implement simple prototype of executor

**Comment by 0pdd** [comment]
@c71n93 2 puzzles [#14](https://github.com/Tea-club/ChaiVM/issues/14), [#15](https://github.com/Tea-club/ChaiVM/issues/15) are still not solved.

**Comment by 0pdd** [comment]
@c71n93 5 puzzles [#15](https://github.com/Tea-club/ChaiVM/issues/15), [#18](https://github.com/Tea-club/ChaiVM/issues/18), [#19](https://github.com/Tea-club/ChaiVM/issues/19), [#20](https://github.com/Tea-club/ChaiVM/issues/20), [#21](https://github.com/Tea-club/ChaiVM/issues/21) are still not solved; solved: [#14](https://github.com/Tea-club/ChaiVM/issues/14).

**Comment by 0pdd** [comment]
@c71n93 4 puzzles [#15](https://github.com/Tea-club/ChaiVM/issues/15), [#19](https://github.com/Tea-club/ChaiVM/issues/19), [#20](https://github.com/Tea-club/ChaiVM/issues/20), [#21](https://github.com/Tea-club/ChaiVM/issues/21) are still not solved; solved: [#14](https://github.com/Tea-club/ChaiVM/issues/14), [#18](https://github.com/Tea-club/ChaiVM/issues/18).

**Comment by 0pdd** [comment]
@c71n93 2 puzzles [#15](https://github.com/Tea-club/ChaiVM/issues/15), [#19](https://github.com/Tea-club/ChaiVM/issues/19) are still not solved; solved: [#14](https://github.com/Tea-club/ChaiVM/issues/14), [#18](https://github.com/Tea-club/ChaiVM/issues/18), [#20](https://github.com/Tea-club/ChaiVM/issues/20), [#21](https://github.com/Tea-club/ChaiVM/issues/21).

**Comment by 0pdd** [comment]
@c71n93 2 puzzles [#19](https://github.com/Tea-club/ChaiVM/issues/19), [#49](https://github.com/Tea-club/ChaiVM/issues/49) are still not solved; solved: [#14](https://github.com/Tea-club/ChaiVM/issues/14), [#15](https://github.com/Tea-club/ChaiVM/issues/15), [#18](https://github.com/Tea-club/ChaiVM/issues/18), [#20](https://github.com/Tea-club/ChaiVM/issues/20), [#21](https://github.com/Tea-club/ChaiVM/issues/21).
