### ISSUE TITLE
Add objects

### ISSUE THREAD

**Issue by levBagryansky** [Tea-club/ChaiVM#97]
We need to add objects.

**Comment by 0pdd** [comment]
@levBagryansky 3 puzzles [#100](https://github.com/Tea-club/ChaiVM/issues/100), [#101](https://github.com/Tea-club/ChaiVM/issues/101), [#102](https://github.com/Tea-club/ChaiVM/issues/102) are still not solved.

**Comment by 0pdd** [comment]
@levBagryansky 2 puzzles [#102](https://github.com/Tea-club/ChaiVM/issues/102), [#108](https://github.com/Tea-club/ChaiVM/issues/108) are still not solved; solved: [#100](https://github.com/Tea-club/ChaiVM/issues/100), [#101](https://github.com/Tea-club/ChaiVM/issues/101).
